import os
import argparse
import tempfile
from datetime import datetime
from typing import Tuple

from dotenv import load_dotenv

from schemas import ResearchBriefPayload, ContentEvaluationSchema, CoreBreakthrough, SourceGrounding

load_dotenv()


class Researcher:
    def __init__(self, api_key: str | None = None):
        self.api_key = api_key

    def research(self, topic: str) -> ResearchBriefPayload:
        # Stubbed implementation: return a deterministic ResearchBriefPayload
        now = datetime.utcnow()
        sources = [
            SourceGrounding(
                source_url="https://example.com/article",
                extracted_fact=f"Top finding for {topic}",
                metric_data="n/a",
            )
        ]
        breakthroughs = [
            CoreBreakthrough(title=f"Breakthrough A in {topic}", technical_summary="Summary A."),
            CoreBreakthrough(title=f"Breakthrough B in {topic}", technical_summary="Summary B."),
            CoreBreakthrough(title=f"Breakthrough C in {topic}", technical_summary="Summary C."),
        ]
        return ResearchBriefPayload(timestamp=now, topic=topic, source_grounding=sources, core_breakthroughs=breakthroughs)


class Writer:
    def generate(self, brief: ResearchBriefPayload) -> str:
        lines = [f"# {brief.topic}\n", "Generated by Writer Agent.\n"]
        for i, b in enumerate(brief.core_breakthroughs, start=1):
            lines.append(f"## {i}. {b.title}\n")
            lines.append(f"{b.technical_summary}\n\n")
        lines.append("\n*Sources:*\n")
        for s in brief.source_grounding:
            lines.append(f"- {s.source_url} — {s.extracted_fact}\n")
        return "\n".join(lines)


class Editor:
    def evaluate(self, draft: str, brief: ResearchBriefPayload) -> ContentEvaluationSchema:
        # Very small heuristic: ensure each breakthrough title appears in draft
        missing = []
        for b in brief.core_breakthroughs:
            if b.title not in draft:
                missing.append(b.title)
        if missing:
            return ContentEvaluationSchema(
                evaluation_status="REJECTED",
                score_metrics={
                    "factual_alignment_score": 0.0,
                    "formatting_compliance": False,
                },
                feedback_logs=f"Missing breakthroughs in draft: {missing}",
            )
        return ContentEvaluationSchema(
            evaluation_status="APPROVED",
            score_metrics={
                "factual_alignment_score": 1.0,
                "formatting_compliance": True,
            },
            feedback_logs="",
        )


def atomic_write(path: str, content: str) -> None:
    dirpath = os.path.dirname(path) or "."
    with tempfile.NamedTemporaryFile("w", delete=False, dir=dirpath) as tf:
        tf.write(content)
        tmpname = tf.name
    os.replace(tmpname, path)


def run_workflow(topic: str, output_file: str = "final_output.md", verbose: bool = False) -> Tuple[ContentEvaluationSchema, str]:
    researcher = Researcher(api_key=os.getenv("SERPER_API_KEY"))
    writer = Writer()
    editor = Editor()

    brief = researcher.research(topic)
    if verbose:
        print("[Researcher] brief=", brief.json())

    draft = writer.generate(brief)
    if verbose:
        print("[Writer] draft preview:\n", draft[:1000])

    evaluation = editor.evaluate(draft, brief)
    if verbose:
        print("[Editor] evaluation=", evaluation.json())

    if evaluation.evaluation_status == "APPROVED":
        atomic_write(output_file, draft)
        if verbose:
            print(f"Wrote approved draft to {output_file}")
    else:
        if verbose:
            print("Draft rejected; not writing output. Feedback:", evaluation.feedback_logs)

    return evaluation, output_file


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the CrewAI MAS workflow (stubbed).")
    parser.add_argument("--topic", required=True, help="Research topic")
    parser.add_argument("--output", default="final_output.md", help="Output file path")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    run_workflow(args.topic, args.output, args.verbose)
